name: "05_ElasticBeanStalk_WebApp"
on:
  workflow_dispatch:

jobs:
  Plan_Dev:
    if: github.ref == 'refs/heads/develop'
    uses: RekhuGopal/gitreusableflows/.github/workflows/aws_tf_plan.yml@develop
    with:
      path: ElasticBeanStalk
      tf_vars_file: dev.tfvars
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

  Deploy_Dev:
    needs: Plan_Dev
    uses: RekhuGopal/gitreusableflows/.github/workflows/aws_tf_appy.yml@develop
    with:
      path: ElasticBeanStalk
      tf_vars_file: dev.tfvars
      gh_environment: dev
    secrets:
      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}